INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('109', '25 de Mayo‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('001', 'Adolfo Alsina‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('002', 'Alberti‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('003', 'Alte. Brown‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('128', 'Ameghino‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('010', 'Arrecifes‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('004', 'Avellaneda‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('005', 'Ayacucho‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('006', 'Azul‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('007', 'Bahia Blanca‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('008', 'Balcarce‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('009', 'Baradero‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('053', 'Benito Juarez‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('120', 'Berazategui‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('114', 'Berisso‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('011', 'Bolivar‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('012', 'Bragado‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('014', 'Campana‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('015', 'Canuelas‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('121', 'Cap. Sarmiento‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('016', 'Carlos Casares‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('017', 'Carlos Tejedor‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('018', 'Carmen de Areco‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('079', 'Carmen de Patagones‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('020', 'Castelli‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('026', 'Chacabuco‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('027', 'Chascomus‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('028', 'Chivilcoy‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('013', 'Cnel. Brandsen‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('022', 'Cnel. Dorrego‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('023', 'Cnel. Pringles‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('113', 'Cnel. Rosales‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('024', 'Cnel. Suarez‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('021', 'Colon‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('019', 'Daireaux‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('029', 'Dolores‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('030', 'E. Echeverria‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('115', 'Ensenada‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('118', 'Escobar‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('031', 'Ex.de la Cruz‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('130', 'Ezeiza‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('032', 'Fcio. Varela‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('051', 'Gonzalez Chavez‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('033', 'Gral. Alvarado‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('034', 'Gral. Alvear‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('035', 'Gral. Arenales‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('036', 'Gral. Belgrano‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('037', 'Gral. Guido‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('040', 'Gral. Lamadrid‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('041', 'Gral. Las Heras‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('042', 'Gral. Lavalle‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('039', 'Gral. Madariaga‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('043', 'Gral. Paz‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('044', 'Gral. Pinto‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('045', 'Gral. Pueyrredon‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('046', 'Gral. Rodriguez‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('049', 'Gral. Viamonte‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('050', 'Gral. Villegas‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('052', 'Guamini‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('119', 'Hipolito Irigoyen‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('135', 'Hurlingham‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('136', 'Ituzaingo‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('132', 'J. C. Paz‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('054', 'Junin‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('059', 'L. N. Alem‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('123', 'La Costa‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('070', 'La Matanza‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('055', 'La Plata‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('025', 'Lanus‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('056', 'Laprida‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('058', 'Las Flores‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('137', 'Lezama‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('060', 'Lincoln‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('061', 'Loberia‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('062', 'Lobos‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('063', 'Lomas de Zamora‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('064', 'Lujan‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('065', 'Magdalena‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('066', 'Maipu‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('133', 'Malvinas Argentinas‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('069', 'Mar Chiquita‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('068', 'Marcos Paz‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('071', 'Mercedes‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('072', 'Merlo‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('073', 'Monte‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('126', 'Monte Hermoso‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('074', 'Moreno‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('101', 'Moron‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('075', 'Navarro‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('076', 'Necochea‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('077', 'Nueve de Julio‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('078', 'Olavarria‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('080', 'Pehuajo‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('081', 'Pellegrini‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('082', 'Pergamino‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('083', 'Pila‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('084', 'Pilar‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('124', 'Pinamar‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('129', 'Presidente Peron‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('085', 'Puan‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('134', 'Punta Indio‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('086', 'Quilmes‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('087', 'Ramallo‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('088', 'Rauch‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('089', 'Rivadavia‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('090', 'Rojas‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('091', 'Roque Perez‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('095', 'S.A. de Areco‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('094', 'S.A. de Giles‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('092', 'Saavedra‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('093', 'Saladillo‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('122', 'Salliquelo‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('067', 'Salto‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('116', 'San Cayetano‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('096', 'San Fernando‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('097', 'San Isidro‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('047', 'San Martin‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('131', 'San Miguel‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('098', 'San Nicolas‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('099', 'San Pedro‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('100', 'San Vicente‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('102', 'Suipacha‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('103', 'Tandil‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('104', 'Tapalque‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('057', 'Tigre‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('105', 'Tordillo‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('106', 'Tornquist‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('107', 'Trenque Lauquen‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('108', 'Tres Arroyos‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('117', 'Tres de Febrero‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('127', 'Tres Lomas‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('125', 'Villa Gesell‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('111', 'Villarino‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('110', 'Vte. Lopez‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('038', 'Zarate‎', '1');

INSERT INTO `owner_rental_db`.`localidades` (`idLocalidad`, `idPartido`, `nombre`, `codPostal`, `habilitado`) VALUES 	('001', '109‎', 'DEL VALLE', '6509‎', '1');

