INSERT INTO `owner_rental_db`.`usuarios` 	SET `idUsuario`= '1' , `nombre` = 'UTN', `apellido` = 'FRGP', `dni` = '11111', `mail` = 'utn@frgp.com', `fechaNac` = STR_TO_DATE('01/01/1990','%d/%m/%Y'), `usuario` = 'utnfrgp', `clave` = 'utn123', `sexo` = '1', `rutaFotoPerfil` = 'imagenes/usuarios/Usuario_1/fotoUsuario_1.jpg', `admin` = '1', `puntaje` = '0', `habilitado` = '1', `fechaAlta` = STR_TO_DATE('01/01/2019','%d/%m/%Y') ,`fechaUltConexion` = STR_TO_DATE('01/01/1900','%d/%m/%Y'), `verificado` = '0';
INSERT INTO `owner_rental_db`.`usuarios` 	SET `idUsuario`= '2' , `nombre` = 'David', `apellido` = 'Martinez', `dni` = '22222', `mail` = 'dmartinez@gmail.com', `fechaNac` = STR_TO_DATE('21/11/1991','%d/%m/%Y'), `usuario` = 'dm123', `clave` = 'dm123', `sexo` = '1', `rutaFotoPerfil` = '', `admin` = '1', `puntaje` = '5', `habilitado` = '1', `fechaAlta` = STR_TO_DATE('01/01/2019','%d/%m/%Y') ,`fechaUltConexion` = STR_TO_DATE('01/01/1900','%d/%m/%Y'), `verificado` = '1';
INSERT INTO `owner_rental_db`.`usuarios` 	SET `idUsuario`= '3' , `nombre` = 'José', `apellido` = 'Escobar', `dni` = '33333', `mail` = 'jescobar@gmail.com', `fechaNac` = STR_TO_DATE('31/12/2000','%d/%m/%Y'), `usuario` = 'je123', `clave` = 'je123', `sexo` = '1', `rutaFotoPerfil` = 'imagenes/usuarios/Usuario_3/fotoUsuario_3.jpg', `admin` = '1', `puntaje` = '5', `habilitado` = '1', `fechaAlta` = STR_TO_DATE('01/01/2019','%d/%m/%Y') ,`fechaUltConexion` = STR_TO_DATE('01/01/1900','%d/%m/%Y'), `verificado` = '1';
INSERT INTO `owner_rental_db`.`usuarios` 	SET `idUsuario`= '4' , `nombre` = 'Gabriela', `apellido` = 'Quevedo', `dni` = '44444', `mail` = 'gquevedo@gmail.com', `fechaNac` = STR_TO_DATE('21/11/1993','%d/%m/%Y'), `usuario` = 'gq123', `clave` = 'gq123', `sexo` = '0', `rutaFotoPerfil` = 'imagenes/usuarios/Usuario_4/fotoUsuario_4.jpg', `admin` = '0', `puntaje` = '4', `habilitado` = '1', `fechaAlta` = STR_TO_DATE('01/03/2019','%d/%m/%Y') ,`fechaUltConexion` = STR_TO_DATE('01/01/1900','%d/%m/%Y'), `verificado` = '1';
INSERT INTO `owner_rental_db`.`usuarios` 	SET `idUsuario`= '5' , `nombre` = 'Santiago', `apellido` = 'López', `dni` = '55555', `mail` = 'slopez@gmail.com', `fechaNac` = STR_TO_DATE('21/11/1994','%d/%m/%Y'), `usuario` = 'sl123', `clave` = 'sl123', `sexo` = '1', `rutaFotoPerfil` = 'imagenes/usuarios/Usuario_5/fotoUsuario_5.jpg', `admin` = '0', `puntaje` = '3', `habilitado` = '1', `fechaAlta` = STR_TO_DATE('01/02/2019','%d/%m/%Y') ,`fechaUltConexion` = STR_TO_DATE('01/01/1900','%d/%m/%Y'), `verificado` = '0';

INSERT INTO `owner_rental_db`.`tiposalojamientos` (`idTipoAlojamiento`, `descripcion`, `habilitado`) VALUES	('1', 'Casa', '1');
INSERT INTO `owner_rental_db`.`tiposalojamientos` (`idTipoAlojamiento`, `descripcion`, `habilitado`) VALUES	('2', 'Cabaña', '1');
INSERT INTO `owner_rental_db`.`tiposalojamientos` (`idTipoAlojamiento`, `descripcion`, `habilitado`) VALUES	('3', 'Departamento', '1');
INSERT INTO `owner_rental_db`.`tiposalojamientos` (`idTipoAlojamiento`, `descripcion`, `habilitado`) VALUES	('4', 'Hotel', '1');
INSERT INTO `owner_rental_db`.`tiposalojamientos` (`idTipoAlojamiento`, `descripcion`, `habilitado`) VALUES	('5', 'Suite', '1');
INSERT INTO `owner_rental_db`.`tiposalojamientos` (`idTipoAlojamiento`, `descripcion`, `habilitado`) VALUES	('6', 'Hostel', '1');

INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('096', 'San Fernando‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('097', 'San Isidro‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('057', 'Tigre‎', '1');
INSERT INTO `owner_rental_db`.`partidos` (`idPartido`, `nombre`, `habilitado`) VALUES	('110', 'Vte. Lopez‎', '1');

INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2275',`idPartido`= '096',`nombre`= 'DOCTOR ALBERT SCHWEITZER (PARADA FCGM)',`codPostal`= '1644',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2276',`idPartido`= '096',`nombre`= 'VICTORIA',`codPostal`= '1644',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2277',`idPartido`= '096',`nombre`= 'BARRIO SAN JORGE (SAN FERNANDO-PDO. SAN FERNANDO)',`codPostal`= '1646',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2278',`idPartido`= '096',`nombre`= 'SAN FERNANDO',`codPostal`= '1646',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2279',`idPartido`= '096',`nombre`= 'VILLA DEL CARMEN (SAN FERNANDO-PDO. SAN FERNANDO)',`codPostal`= '1646',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2280',`idPartido`= '096',`nombre`= 'VIRREYES',`codPostal`= '1646',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2281',`idPartido`= '096',`nombre`= 'ARROYO ANDRESITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2282',`idPartido`= '096',`nombre`= 'ARROYO ARROYON',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2283',`idPartido`= '096',`nombre`= 'ARROYO ARROYON DE FELICARIA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2284',`idPartido`= '096',`nombre`= 'ARROYO BALDOSAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2285',`idPartido`= '096',`nombre`= 'ARROYO BALTICO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2286',`idPartido`= '096',`nombre`= 'ARROYO BANCO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2287',`idPartido`= '096',`nombre`= 'ARROYO BOCA FALSA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2288',`idPartido`= '096',`nombre`= 'ARROYO BORASSO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2289',`idPartido`= '096',`nombre`= 'ARROYO BORCHES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2290',`idPartido`= '096',`nombre`= 'ARROYO BUENA VISTA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2291',`idPartido`= '096',`nombre`= 'ARROYO BUSTO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2292',`idPartido`= '096',`nombre`= 'ARROYO CAGUANE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2293',`idPartido`= '096',`nombre`= 'ARROYO CAMACHITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2294',`idPartido`= '096',`nombre`= 'ARROYO CAMACHO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2295',`idPartido`= '096',`nombre`= 'ARROYO CANALETON',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2296',`idPartido`= '096',`nombre`= 'ARROYO CANCHA LARGA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2297',`idPartido`= '096',`nombre`= 'ARROYO CANELONES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2298',`idPartido`= '096',`nombre`= 'ARROYO CAPITAN CHICO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2299',`idPartido`= '096',`nombre`= 'ARROYO CAPITANCITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2300',`idPartido`= '096',`nombre`= 'ARROYO CARABALLO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2301',`idPartido`= '096',`nombre`= 'ARROYO CARABELAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2302',`idPartido`= '096',`nombre`= 'ARROYO CARACOLES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2303',`idPartido`= '096',`nombre`= 'ARROYO CARAGUATA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2304',`idPartido`= '096',`nombre`= 'ARROYO CARANCHO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2305',`idPartido`= '096',`nombre`= 'ARROYO CARAPUATI',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2306',`idPartido`= '096',`nombre`= 'ARROYO CARLOS M. NOEL',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2307',`idPartido`= '096',`nombre`= 'ARROYO CARNICERO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2308',`idPartido`= '096',`nombre`= 'ARROYO CARPINCHO (PDO. SAN FERNANDO)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2309',`idPartido`= '096',`nombre`= 'ARROYO CHANA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2310',`idPartido`= '096',`nombre`= 'ARROYO CHANACILIO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2311',`idPartido`= '096',`nombre`= 'ARROYO CHANACITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2312',`idPartido`= '096',`nombre`= 'ARROYO CHILENO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2313',`idPartido`= '096',`nombre`= 'ARROYO CHIQUERITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2314',`idPartido`= '096',`nombre`= 'ARROYO CHIQUERO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2315',`idPartido`= '096',`nombre`= 'ARROYO CHIVICO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2316',`idPartido`= '096',`nombre`= 'ARROYO CHURRASCO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2317',`idPartido`= '096',`nombre`= 'ARROYO CIEGO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2318',`idPartido`= '096',`nombre`= 'ARROYO CIEGO DEL ESTUDIANTE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2319',`idPartido`= '096',`nombre`= 'ARROYO CIEGUITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2320',`idPartido`= '096',`nombre`= 'ARROYO CIERVO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2321',`idPartido`= '096',`nombre`= 'ARROYO CONCEPCION',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2322',`idPartido`= '096',`nombre`= 'ARROYO CONFITERITO PALMAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2323',`idPartido`= '096',`nombre`= 'ARROYO CONFITERO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2324',`idPartido`= '096',`nombre`= 'ARROYO CORREA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2325',`idPartido`= '096',`nombre`= 'ARROYO CORRENTINO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2326',`idPartido`= '096',`nombre`= 'ARROYO CORRENTOSO (BARCA GRANDE)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2327',`idPartido`= '096',`nombre`= 'ARROYO CORTO (TIGRE-PDO. CAMPANA)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2328',`idPartido`= '096',`nombre`= 'ARROYO CRUCES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2329',`idPartido`= '096',`nombre`= 'ARROYO CRUZ COLORADA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2330',`idPartido`= '096',`nombre`= 'ARROYO CRUZ DEL CAMBADO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2331',`idPartido`= '096',`nombre`= 'ARROYO CRUZ DEL SAUCE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2332',`idPartido`= '096',`nombre`= 'ARROYO CUARENTA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2333',`idPartido`= '096',`nombre`= 'ARROYO CUEVAS MALAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2334',`idPartido`= '096',`nombre`= 'ARROYO CURUBICA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2335',`idPartido`= '096',`nombre`= 'ARROYO DE LAS GAVIOTAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2336',`idPartido`= '096',`nombre`= 'ARROYO DE LOS NOGALES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2337',`idPartido`= '096',`nombre`= 'ARROYO DE LOS TIGRES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2338',`idPartido`= '096',`nombre`= 'ARROYO DEL CANAL',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2339',`idPartido`= '096',`nombre`= 'ARROYO DEL POBRE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2340',`idPartido`= '096',`nombre`= 'ARROYO DENTUDO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2341',`idPartido`= '096',`nombre`= 'ARROYO DESAGUADERO DE BORCHES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2342',`idPartido`= '096',`nombre`= 'ARROYO DESAGUADERO DEL SAUCE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2343',`idPartido`= '096',`nombre`= 'ARROYO DESENGA#O',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2344',`idPartido`= '096',`nombre`= 'ARROYO DIABLO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2345',`idPartido`= '096',`nombre`= 'ARROYO DOMINGUITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2346',`idPartido`= '096',`nombre`= 'ARROYO DORADO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2347',`idPartido`= '096',`nombre`= 'ARROYO DOS PUNTAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2348',`idPartido`= '096',`nombre`= 'ARROYO DURAZNITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2349',`idPartido`= '096',`nombre`= 'ARROYO DURAZNO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2350',`idPartido`= '096',`nombre`= 'ARROYO EDUARDO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2351',`idPartido`= '096',`nombre`= 'ARROYO EL CAZADOR',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2352',`idPartido`= '096',`nombre`= 'ARROYO EL NEGRO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2353',`idPartido`= '096',`nombre`= 'ARROYO EL PLATA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2354',`idPartido`= '096',`nombre`= 'ARROYO EL RODEO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2355',`idPartido`= '096',`nombre`= 'ARROYO ESPADA#A',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2356',`idPartido`= '096',`nombre`= 'ARROYO ESPERA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2357',`idPartido`= '096',`nombre`= 'ARROYO ESPERA GRANDE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2358',`idPartido`= '096',`nombre`= 'ARROYO ESPERITA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2359',`idPartido`= '096',`nombre`= 'ARROYO ESTUDIANTE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2360',`idPartido`= '096',`nombre`= 'ARROYO ESTUDIANTE CHICO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2361',`idPartido`= '096',`nombre`= 'ARROYO FELICARIA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2362',`idPartido`= '096',`nombre`= 'ARROYO FELIPE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2363',`idPartido`= '096',`nombre`= 'ARROYO FELIX',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2364',`idPartido`= '096',`nombre`= 'ARROYO FERMIN',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2365',`idPartido`= '096',`nombre`= 'ARROYO FFREDES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2366',`idPartido`= '096',`nombre`= 'ARROYO FONTANA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2367',`idPartido`= '096',`nombre`= 'ARROYO FRANCISCO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2368',`idPartido`= '096',`nombre`= 'ARROYO FULMINANTE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2369',`idPartido`= '096',`nombre`= 'ARROYO GALLITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2370',`idPartido`= '096',`nombre`= 'ARROYO GALLO FIAMBRE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2371',`idPartido`= '096',`nombre`= 'ARROYO GALPON',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2372',`idPartido`= '096',`nombre`= 'ARROYO GAMBADO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2373',`idPartido`= '096',`nombre`= 'ARROYO GAVIOTAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2374',`idPartido`= '096',`nombre`= 'ARROYO GELVEZ',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2375',`idPartido`= '096',`nombre`= 'ARROYO GLORIETA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2376',`idPartido`= '096',`nombre`= 'ARROYO GRANDE (TIGRE-PDO. SAN FERNANDO)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2377',`idPartido`= '096',`nombre`= 'ARROYO GUAYRACA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2378',`idPartido`= '096',`nombre`= 'ARROYO GUAZU NAMBI',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2379',`idPartido`= '096',`nombre`= 'ARROYO GUAZUCITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2380',`idPartido`= '096',`nombre`= 'ARROYO GUTIERREZ',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2381',`idPartido`= '096',`nombre`= 'ARROYO HERMANA GRANDE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2382',`idPartido`= '096',`nombre`= 'ARROYO HERMANA PRIMERA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2383',`idPartido`= '096',`nombre`= 'ARROYO HERMANA SEGUNDA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2384',`idPartido`= '096',`nombre`= 'ARROYO IDAHONE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2385',`idPartido`= '096',`nombre`= 'ARROYO INCA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2386',`idPartido`= '096',`nombre`= 'ARROYO LA BARQUITA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2387',`idPartido`= '096',`nombre`= 'ARROYO LA CASILLA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2388',`idPartido`= '096',`nombre`= 'ARROYO LA CASTILLA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2389',`idPartido`= '096',`nombre`= 'ARROYO LA GLORIETA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2390',`idPartido`= '096',`nombre`= 'ARROYO LA HORCA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2391',`idPartido`= '096',`nombre`= 'ARROYO LA LINDA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2392',`idPartido`= '096',`nombre`= 'ARROYO LA NEGRA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2393',`idPartido`= '096',`nombre`= 'ARROYO LA RAYA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2394',`idPartido`= '096',`nombre`= 'ARROYO LAGUNA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2395',`idPartido`= '096',`nombre`= 'ARROYO LAGUNA GRANDE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2396',`idPartido`= '096',`nombre`= 'ARROYO LARGO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2397',`idPartido`= '096',`nombre`= 'ARROYO LAS BALDOSAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2398',`idPartido`= '096',`nombre`= 'ARROYO LAS BOGAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2399',`idPartido`= '096',`nombre`= 'ARROYO LAS CA#AS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2400',`idPartido`= '096',`nombre`= 'ARROYO LAS CASAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2401',`idPartido`= '096',`nombre`= 'ARROYO LAS NACIONES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2402',`idPartido`= '096',`nombre`= 'ARROYO LAS PIEDRAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2403',`idPartido`= '096',`nombre`= 'ARROYO LAS ROSAS (TIGRE-PDO. TIGRE)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2404',`idPartido`= '096',`nombre`= 'ARROYO LAS VIBORAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2405',`idPartido`= '096',`nombre`= 'ARROYO LAS VIUDAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2406',`idPartido`= '096',`nombre`= 'ARROYO LAZARO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2407',`idPartido`= '096',`nombre`= 'ARROYO LEIVA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2408',`idPartido`= '096',`nombre`= 'ARROYO LIMA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2409',`idPartido`= '096',`nombre`= 'ARROYO LOS GRILLOS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2410',`idPartido`= '096',`nombre`= 'ARROYO LOS LOBOS (PDO. SAN FERNANDO)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2411',`idPartido`= '096',`nombre`= 'ARROYO LOS NEGROS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2412',`idPartido`= '096',`nombre`= 'ARROYO MACHADO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2413',`idPartido`= '096',`nombre`= 'ARROYO MALO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2414',`idPartido`= '096',`nombre`= 'ARROYO MALVINAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2415',`idPartido`= '096',`nombre`= 'ARROYO MANZANO DE LA BARCA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2416',`idPartido`= '096',`nombre`= 'ARROYO MANZANO DE MEDINA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2417',`idPartido`= '096',`nombre`= 'ARROYO MARTINEZ (TIGRE-PDO. TIGRE)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2418',`idPartido`= '096',`nombre`= 'ARROYO MEDINA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2419',`idPartido`= '096',`nombre`= 'ARROYO MELINDRE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2420',`idPartido`= '096',`nombre`= 'ARROYO MENDEZ CHICO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2421',`idPartido`= '096',`nombre`= 'ARROYO MENDEZ GRANDE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2422',`idPartido`= '096',`nombre`= 'ARROYO MORAN',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2423',`idPartido`= '096',`nombre`= 'ARROYO MORANCITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2424',`idPartido`= '096',`nombre`= 'ARROYO MORAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2425',`idPartido`= '096',`nombre`= 'ARROYO NACIONES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2426',`idPartido`= '096',`nombre`= 'ARROYO NARANJITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2427',`idPartido`= '096',`nombre`= 'ARROYO NARANJO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2428',`idPartido`= '096',`nombre`= 'ARROYO NARANJO BORCHES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2429',`idPartido`= '096',`nombre`= 'ARROYO NEGRO (TIGRE-PDO. CAMPANA)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2430',`idPartido`= '096',`nombre`= 'ARROYO NOGAL',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2431',`idPartido`= '096',`nombre`= 'ARROYO NUEVE DE JULIO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2432',`idPartido`= '096',`nombre`= 'ARROYO PACIENCIA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2433',`idPartido`= '096',`nombre`= 'ARROYO PACIFICO (CAPITAN)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2434',`idPartido`= '096',`nombre`= 'ARROYO PACIFICO (DE LA SERNA)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2435',`idPartido`= '096',`nombre`= 'ARROYO PACU',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2436',`idPartido`= '096',`nombre`= 'ARROYO PAJAL',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2437',`idPartido`= '096',`nombre`= 'ARROYO PAJARITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2438',`idPartido`= '096',`nombre`= 'ARROYO PANTANOCITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2439',`idPartido`= '096',`nombre`= 'ARROYO PANTANOSO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2440',`idPartido`= '096',`nombre`= 'ARROYO PARAGUAY',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2441',`idPartido`= '096',`nombre`= 'ARROYO PATI',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2442',`idPartido`= '096',`nombre`= 'ARROYO PAYCARABI',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2443',`idPartido`= '096',`nombre`= 'ARROYO PAYCARABICITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2444',`idPartido`= '096',`nombre`= 'ARROYO PINERAL',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2445',`idPartido`= '096',`nombre`= 'ARROYO POLVORA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2446',`idPartido`= '096',`nombre`= 'ARROYO PORFIADO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2447',`idPartido`= '096',`nombre`= 'ARROYO PRIMERA HERMANA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2448',`idPartido`= '096',`nombre`= 'ARROYO RAMA NEGRA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2449',`idPartido`= '096',`nombre`= 'ARROYO RAMALLO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2450',`idPartido`= '096',`nombre`= 'ARROYO RAYA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2451',`idPartido`= '096',`nombre`= 'ARROYO REMANCITO (CARABELAS)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2452',`idPartido`= '096',`nombre`= 'ARROYO REMANCITO (MENDEZ GRANDE)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2453',`idPartido`= '096',`nombre`= 'ARROYO REYES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2454',`idPartido`= '096',`nombre`= 'ARROYO RICO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2455',`idPartido`= '096',`nombre`= 'ARROYO RINCONADA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2456',`idPartido`= '096',`nombre`= 'ARROYO RODEO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2457',`idPartido`= '096',`nombre`= 'ARROYO ROMANCITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2458',`idPartido`= '096',`nombre`= 'ARROYO ROMERO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2459',`idPartido`= '096',`nombre`= 'ARROYO SABALOS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2460',`idPartido`= '096',`nombre`= 'ARROYO SAN SALVADOR',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2461',`idPartido`= '096',`nombre`= 'ARROYO SANTA ROSA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2462',`idPartido`= '096',`nombre`= 'ARROYO SANTO DOMINGO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2463',`idPartido`= '096',`nombre`= 'ARROYO SAUCE LLORON',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2464',`idPartido`= '096',`nombre`= 'ARROYO SEGUNDA HERMANA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2465',`idPartido`= '096',`nombre`= 'ARROYO SURUBI',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2466',`idPartido`= '096',`nombre`= 'ARROYO TARARIRAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2467',`idPartido`= '096',`nombre`= 'ARROYO TELA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2468',`idPartido`= '096',`nombre`= 'ARROYO TIBER',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2469',`idPartido`= '096',`nombre`= 'ARROYO TIBURON',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2470',`idPartido`= '096',`nombre`= 'ARROYO TOLEDO (PALMAS)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2471',`idPartido`= '096',`nombre`= 'ARROYO TOLEDO (PARANA MINI)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2472',`idPartido`= '096',`nombre`= 'ARROYO TORITO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2473',`idPartido`= '096',`nombre`= 'ARROYO TORO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2474',`idPartido`= '096',`nombre`= 'ARROYO TRES SARGENTOS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2475',`idPartido`= '096',`nombre`= 'ARROYO TUYUPARE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2476',`idPartido`= '096',`nombre`= 'ARROYO VEINTICINCO DE NOVIEMBRE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2477',`idPartido`= '096',`nombre`= 'ARROYO VERON',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2478',`idPartido`= '096',`nombre`= 'ARROYO VICO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2479',`idPartido`= '096',`nombre`= 'BOCA CARABELAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2480',`idPartido`= '096',`nombre`= 'BOCA DE LA CRUZ COLORADA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2481',`idPartido`= '096',`nombre`= 'BOCA DEL ARROYO ESTUDIANTE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2482',`idPartido`= '096',`nombre`= 'BOCA DEL TORO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2483',`idPartido`= '096',`nombre`= 'CANAL A',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2484',`idPartido`= '096',`nombre`= 'CANAL C',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2485',`idPartido`= '096',`nombre`= 'CANAL CINCO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2486',`idPartido`= '096',`nombre`= 'CANAL CUATRO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2487',`idPartido`= '096',`nombre`= 'CANAL DE LA SERNA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2488',`idPartido`= '096',`nombre`= 'CANAL DEL ESTE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2489',`idPartido`= '096',`nombre`= 'CANAL DOS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2490',`idPartido`= '096',`nombre`= 'CANAL GOBERNADOR ARANA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2491',`idPartido`= '096',`nombre`= 'CANAL GOBERNADOR ARIAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2492',`idPartido`= '096',`nombre`= 'CANAL GOBERNADOR DE LA SERNA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2493',`idPartido`= '096',`nombre`= 'CANAL HAMBRIENTOS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2494',`idPartido`= '096',`nombre`= 'CANAL HONDA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2495',`idPartido`= '096',`nombre`= 'CANAL LAURENTINO COMAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2496',`idPartido`= '096',`nombre`= 'CANAL N" 1',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2497',`idPartido`= '096',`nombre`= 'CANAL N" 2',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2498',`idPartido`= '096',`nombre`= 'CANAL N" 3',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2499',`idPartido`= '096',`nombre`= 'CANAL N" 4',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2500',`idPartido`= '096',`nombre`= 'CANAL N" 5',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2501',`idPartido`= '096',`nombre`= 'CANAL PICARDO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2502',`idPartido`= '096',`nombre`= 'CANAL TRES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2503',`idPartido`= '096',`nombre`= 'CANAL UNION',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2504',`idPartido`= '096',`nombre`= 'CANAL UNO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2505',`idPartido`= '096',`nombre`= 'CANAL URION',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2506',`idPartido`= '096',`nombre`= 'CANAL VILLANUEVA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2507',`idPartido`= '096',`nombre`= 'CHA#A-MINI',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2508',`idPartido`= '096',`nombre`= 'CUARTELES CARABELAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2509',`idPartido`= '096',`nombre`= 'CUATRO BOCAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2510',`idPartido`= '096',`nombre`= 'EL CORRENTOSO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2511',`idPartido`= '096',`nombre`= 'ESTACION FORESTAL DOMINGO FAUSTINO SARMIENTO (DELTA)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2512',`idPartido`= '096',`nombre`= 'GUAZU Y MANZANO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2513',`idPartido`= '096',`nombre`= 'GUAZU Y NARANJO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2514',`idPartido`= '096',`nombre`= 'LA BARQUITA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2515',`idPartido`= '096',`nombre`= 'LAGUNA DE BORCHES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2516',`idPartido`= '096',`nombre`= 'LAGUNA DE LA BARCA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2517',`idPartido`= '096',`nombre`= 'LAGUNA LAGUNITA',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2518',`idPartido`= '096',`nombre`= 'PARANA MINI',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2519',`idPartido`= '096',`nombre`= 'PAY CARABI',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2520',`idPartido`= '096',`nombre`= 'RECREO EL MARQUES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2521',`idPartido`= '096',`nombre`= 'RIO BARCA GRANDE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2522',`idPartido`= '096',`nombre`= 'RIO CAPITAN',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2523',`idPartido`= '096',`nombre`= 'RIO CARABELAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2524',`idPartido`= '096',`nombre`= 'RIO CARABELAS GRANDES',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2525',`idPartido`= '096',`nombre`= 'RIO CARAPACHAY',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2526',`idPartido`= '096',`nombre`= 'RIO LUJAN (TIGRE-PDO. TIGRE)',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2527',`idPartido`= '096',`nombre`= 'RIO PARANA DE LAS PALMAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2528',`idPartido`= '096',`nombre`= 'RIO PARANA MINI',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2529',`idPartido`= '096',`nombre`= 'RIO SAN ANTONIO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2530',`idPartido`= '096',`nombre`= 'RIO SARMIENTO',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2531',`idPartido`= '096',`nombre`= 'RIO TIGRE',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2532',`idPartido`= '096',`nombre`= 'TRES BOCAS',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2533',`idPartido`= '096',`nombre`= 'VARADERO DEL MINI',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2534',`idPartido`= '096',`nombre`= 'ZANJA GUALTIERI',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2535',`idPartido`= '096',`nombre`= 'ZANJA TAMAGNI',`codPostal`= '1649',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2536',`idPartido`= '097',`nombre`= 'BARRIO OBRERO FERROVIARIO',`codPostal`= '1607',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2537',`idPartido`= '097',`nombre`= 'BARRIO STELLA MARIS',`codPostal`= '1607',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2538',`idPartido`= '097',`nombre`= 'JOSE MARTI',`codPostal`= '1607',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2539',`idPartido`= '097',`nombre`= 'VILLA ADELINA',`codPostal`= '1607',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2540',`idPartido`= '097',`nombre`= 'BOULOGNE',`codPostal`= '1609',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2541',`idPartido`= '097',`nombre`= 'BOULOGNE SUR MER',`codPostal`= '1609',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2542',`idPartido`= '097',`nombre`= 'ACASSUSO',`codPostal`= '1640',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2543',`idPartido`= '097',`nombre`= 'BARRIO VILLA PRIMAVERA',`codPostal`= '1640',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2544',`idPartido`= '097',`nombre`= 'MARTINEZ',`codPostal`= '1640',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2545',`idPartido`= '097',`nombre`= 'BARRIO BOATING CLUB',`codPostal`= '1642',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2546',`idPartido`= '097',`nombre`= 'BARRIO GENERAL PUEYRREDON',`codPostal`= '1642',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2547',`idPartido`= '097',`nombre`= 'MONTE VIEJO',`codPostal`= '1642',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2548',`idPartido`= '097',`nombre`= 'SAN ISIDRO',`codPostal`= '1642',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2549',`idPartido`= '097',`nombre`= 'BECCAR',`codPostal`= '1643',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2717',`idPartido`= '057',`nombre`= 'BARRIO BAIRES',`codPostal`= '1611',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2718',`idPartido`= '057',`nombre`= 'BARRIO DOCTOR RICARDO GUTIERREZ',`codPostal`= '1611',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2719',`idPartido`= '057',`nombre`= 'DON TORCUATO',`codPostal`= '1611',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2720',`idPartido`= '057',`nombre`= 'KILOMETRO 26',`codPostal`= '1611',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2721',`idPartido`= '057',`nombre`= 'SOLANA DEL MONTE',`codPostal`= '1611',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2722',`idPartido`= '057',`nombre`= 'VICEALMIRANTE E. MONTES',`codPostal`= '1611',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2723',`idPartido`= '057',`nombre`= 'ALTO DEL TALAR',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2724',`idPartido`= '057',`nombre`= 'BARRIO EL BOYERO',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2725',`idPartido`= '057',`nombre`= 'BARRIO EL EMBRUJO',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2726',`idPartido`= '057',`nombre`= 'BARRIO EL PEREJIL',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2727',`idPartido`= '057',`nombre`= 'BARRIO EL ZORZAL',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2728',`idPartido`= '057',`nombre`= 'BARRIO ENRIQUE DELFINO',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2729',`idPartido`= '057',`nombre`= 'BARRIO FERRINI',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2730',`idPartido`= '057',`nombre`= 'BARRIO LOS TRONCOS DEL TALAR',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2731',`idPartido`= '057',`nombre`= 'BARRIO RESIDENCIAL ESTANCIA GENERAL PACHECO',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2732',`idPartido`= '057',`nombre`= 'BARRIO RICARDO ROJAS (GENERAL PACHECO-PDO. TIGRE)',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2733',`idPartido`= '057',`nombre`= 'BARRIO RODRIGUEZ',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2734',`idPartido`= '057',`nombre`= 'BARRIO TRONCOS DEL TALAR',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2735',`idPartido`= '057',`nombre`= 'DOCTOR RICARDO ROJAS',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2736',`idPartido`= '057',`nombre`= 'GENERAL PACHECO',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2737',`idPartido`= '057',`nombre`= 'KILOMETRO 31 (APEADERO FCGM)',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2738',`idPartido`= '057',`nombre`= 'LOPEZ CAMELO',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2739',`idPartido`= '057',`nombre`= 'PARQUE SAN LORENZO',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2740',`idPartido`= '057',`nombre`= 'VILLA LAS TUNAS',`codPostal`= '1617',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2741',`idPartido`= '057',`nombre`= 'EL TALAR',`codPostal`= '1618',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2742',`idPartido`= '057',`nombre`= 'BENAVIDEZ',`codPostal`= '1621',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2743',`idPartido`= '057',`nombre`= 'NUEVO PUERTO TIGRE',`codPostal`= '1648',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2744',`idPartido`= '057',`nombre`= 'TIGRE',`codPostal`= '1648',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2745',`idPartido`= '057',`nombre`= 'VILLA LA #ATA',`codPostal`= '1648',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2746',`idPartido`= '057',`nombre`= 'NORDELTA',`codPostal`= '1670',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2885',`idPartido`= '110',`nombre`= 'ARISTOBULO DEL VALLE',`codPostal`= '1602',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2886',`idPartido`= '110',`nombre`= 'DOCTOR ANTONIO CETRANGOLO (PARADA FCGM)',`codPostal`= '1602',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2887',`idPartido`= '110',`nombre`= 'FLORIDA',`codPostal`= '1602',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2888',`idPartido`= '110',`nombre`= 'JUAN B. JUSTO (ESTACION FCGM) (FLORIDA-PDO. VICENTE LOPEZ)',`codPostal`= '1602',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2889',`idPartido`= '110',`nombre`= 'PUENTE SAAVEDRA',`codPostal`= '1602',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2890',`idPartido`= '110',`nombre`= 'VILLA MARTELLI',`codPostal`= '1603',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2891',`idPartido`= '110',`nombre`= 'MUNRO',`codPostal`= '1605',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2892',`idPartido`= '110',`nombre`= 'CARAPACHAY',`codPostal`= '1606',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2893',`idPartido`= '110',`nombre`= 'BARTOLOME MITRE (ESTACION FCGM)',`codPostal`= '1636',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2894',`idPartido`= '110',`nombre`= 'BORGES',`codPostal`= '1636',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2895',`idPartido`= '110',`nombre`= 'LA LUCILA',`codPostal`= '1636',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2896',`idPartido`= '110',`nombre`= 'OLIVOS',`codPostal`= '1636',`habilitado`= '1';
INSERT INTO `owner_rental_db`.`localidades` 	SET `idLocalidad`= '2897',`idPartido`= '110',`nombre`= 'VICENTE LOPEZ',`codPostal`= '1638',`habilitado`= '1';


INSERT INTO `owner_rental_db`.`publicaciones` 	SET `idPublicacion`= '1', `idUsuario` ='1', `idTipoAlojamiento` ='1', `nombre` ='', `descripcion` ='Casa - Test', `idLocalidad` ='2744', `codPostal` ='1648', `coordenadas` ='', `calle` ='Av. alguna parte', `altura` ='3000', `piso` ='0', `dpto` ='0', `supCubierta` ='700', `supDescubierta` ='50', `precioExpensas` ='0', `precioNoche` ='700', `cantPersonas` ='4', `cantAmbientes` ='4', `cantBanios` ='2', `cantHabitaciones` ='2', `fechaAlta` =STR_TO_DATE('30/01/2019','%d/%m/%Y'), `puntaje` ='3.5', `habilitado` ='1', `verificado` ='0';
INSERT INTO `owner_rental_db`.`publicaciones` 	SET `idPublicacion`= '2', `idUsuario` ='1', `idTipoAlojamiento` ='2', `nombre` ='', `descripcion` ='Cabaña  - Test', `idLocalidad` ='2278', `codPostal` ='1646', `coordenadas` ='', `calle` ='Los pasos', `altura` ='2500', `piso` ='0', `dpto` ='0', `supCubierta` ='450', `supDescubierta` ='40', `precioExpensas` ='1500', `precioNoche` ='400', `cantPersonas` ='3', `cantAmbientes` ='4', `cantBanios` ='1', `cantHabitaciones` ='3', `fechaAlta` =STR_TO_DATE('30/12/2018','%d/%m/%Y'), `puntaje` ='2.5', `habilitado` ='1', `verificado` ='0';
INSERT INTO `owner_rental_db`.`publicaciones` 	SET `idPublicacion`= '3', `idUsuario` ='1', `idTipoAlojamiento` ='3', `nombre` ='', `descripcion` ='Dpto - Test', `idLocalidad` ='2278', `codPostal` ='1646', `coordenadas` ='', `calle` ='Av. Italia', `altura` ='2000', `piso` ='4', `dpto` ='b', `supCubierta` ='500', `supDescubierta` ='50', `precioExpensas` ='2000', `precioNoche` ='750', `cantPersonas` ='4', `cantAmbientes` ='6', `cantBanios` ='2', `cantHabitaciones` ='4', `fechaAlta` =STR_TO_DATE('01/01/2019','%d/%m/%Y'), `puntaje` ='4', `habilitado` ='1', `verificado` ='1';
INSERT INTO `owner_rental_db`.`publicaciones` 	SET `idPublicacion`= '4', `idUsuario` ='2', `idTipoAlojamiento` ='4', `nombre` ='', `descripcion` ='Hotel - Test', `idLocalidad` ='2278', `codPostal` ='1646', `coordenadas` ='', `calle` ='Reconquista', `altura` ='1500', `piso` ='0', `dpto` ='0', `supCubierta` ='500', `supDescubierta` ='50', `precioExpensas` ='0', `precioNoche` ='800', `cantPersonas` ='4', `cantAmbientes` ='6', `cantBanios` ='2', `cantHabitaciones` ='4', `fechaAlta` =STR_TO_DATE('01/01/2019','%d/%m/%Y'), `puntaje` ='5', `habilitado` ='1', `verificado` ='1';

INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('4', '1', 'comentario - test 1', STR_TO_DATE('30/11/2018','%d/%m/%Y'), '5', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('2', '1', 'comentario - test 2', STR_TO_DATE('30/11/2018','%d/%m/%Y'), '5', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('3', '2', 'comentario - test 3', STR_TO_DATE('30/12/2018','%d/%m/%Y'), '3', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('4', '2', 'comentario - test 4', STR_TO_DATE('13/01/2019','%d/%m/%Y'), '5', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('5', '2', 'comentario - test 5', STR_TO_DATE('08/01/2019','%d/%m/%Y'), '4', '1');
