INSERT INTO `owner_rental_db`.`usuarios` 	SET `idUsuario`= '1' , `nombre` = 'UTN', `apellido` = 'FRGP', `dni` = '11111', `mail` = 'utn@frgp.com', `fechaNac` = STR_TO_DATE('01/01/1990','%d/%m/%Y'), `usuario` = 'utnfrgp', `clave` = 'utn123', `sexo` = '1', `rutaFotoPerfil` = 'imagenes/usuarios/Usuario_1/fotoUsuario_1.jpg', `admin` = '1', `puntaje` = '0', `habilitado` = '1', `fechaAlta` = STR_TO_DATE('01/01/2019','%d/%m/%Y') ,`fechaUltConexion` = STR_TO_DATE('01/01/1900','%d/%m/%Y'), `verificado` = '0';
INSERT INTO `owner_rental_db`.`usuarios` 	SET `idUsuario`= '2' , `nombre` = 'David', `apellido` = 'Martinez', `dni` = '22222', `mail` = 'dmartinez@gmail.com', `fechaNac` = STR_TO_DATE('21/11/1991','%d/%m/%Y'), `usuario` = 'dm123', `clave` = 'dm123', `sexo` = '1', `rutaFotoPerfil` = '', `admin` = '1', `puntaje` = '5', `habilitado` = '1', `fechaAlta` = STR_TO_DATE('01/01/2019','%d/%m/%Y') ,`fechaUltConexion` = STR_TO_DATE('01/01/1900','%d/%m/%Y'), `verificado` = '1';
INSERT INTO `owner_rental_db`.`usuarios` 	SET `idUsuario`= '3' , `nombre` = 'José', `apellido` = 'Escobar', `dni` = '33333', `mail` = 'jescobar@gmail.com', `fechaNac` = STR_TO_DATE('31/12/2000','%d/%m/%Y'), `usuario` = 'je123', `clave` = 'je123', `sexo` = '1', `rutaFotoPerfil` = 'imagenes/usuarios/Usuario_3/fotoUsuario_3.jpg', `admin` = '1', `puntaje` = '5', `habilitado` = '1', `fechaAlta` = STR_TO_DATE('01/01/2019','%d/%m/%Y') ,`fechaUltConexion` = STR_TO_DATE('01/01/1900','%d/%m/%Y'), `verificado` = '1';
INSERT INTO `owner_rental_db`.`usuarios` 	SET `idUsuario`= '4' , `nombre` = 'Gabriela', `apellido` = 'Quevedo', `dni` = '44444', `mail` = 'gquevedo@gmail.com', `fechaNac` = STR_TO_DATE('21/11/1993','%d/%m/%Y'), `usuario` = 'gq123', `clave` = 'gq123', `sexo` = '0', `rutaFotoPerfil` = 'imagenes/usuarios/Usuario_4/fotoUsuario_4.jpg', `admin` = '0', `puntaje` = '4', `habilitado` = '1', `fechaAlta` = STR_TO_DATE('01/03/2019','%d/%m/%Y') ,`fechaUltConexion` = STR_TO_DATE('01/01/1900','%d/%m/%Y'), `verificado` = '1';
INSERT INTO `owner_rental_db`.`usuarios` 	SET `idUsuario`= '5' , `nombre` = 'Santiago', `apellido` = 'López', `dni` = '55555', `mail` = 'slopez@gmail.com', `fechaNac` = STR_TO_DATE('21/11/1994','%d/%m/%Y'), `usuario` = 'sl123', `clave` = 'sl123', `sexo` = '1', `rutaFotoPerfil` = 'imagenes/usuarios/Usuario_5/fotoUsuario_5.jpg', `admin` = '0', `puntaje` = '3', `habilitado` = '1', `fechaAlta` = STR_TO_DATE('01/02/2019','%d/%m/%Y') ,`fechaUltConexion` = STR_TO_DATE('01/01/1900','%d/%m/%Y'), `verificado` = '0';
INSERT INTO `owner_rental_db`.`usuarios` 	SET `idUsuario`= '6' , `nombre` = 'Lola', `apellido` = 'B', `dni` = '66666', `mail` = 'lolaB@gmail.com', `fechaNac` = STR_TO_DATE('11/03/2013','%d/%m/%Y'), `usuario` = 'lb123', `clave` = 'lb123', `sexo` = '0', `rutaFotoPerfil` = 'imagenes/usuarios/Usuario_5/fotoUsuario_6.jpg', `admin` = '0', `puntaje` = '5', `habilitado` = '1', `fechaAlta` = STR_TO_DATE('01/02/2020','%d/%m/%Y') ,`fechaUltConexion` = STR_TO_DATE('01/01/2000','%d/%m/%Y'), `verificado` = '1';
INSERT INTO `owner_rental_db`.`usuarios` 	SET `idUsuario`= '7' , `nombre` = 'Tomi', `apellido` = 'B', `dni` = '77777', `mail` = 'tomiB@gmail.com', `fechaNac` = STR_TO_DATE('12/10/2010','%d/%m/%Y'), `usuario` = 'tb123', `clave` = 'tb123', `sexo` = '1', `rutaFotoPerfil` = 'imagenes/usuarios/Usuario_5/fotoUsuario_7.jpg', `admin` = '0', `puntaje` = '5', `habilitado` = '1', `fechaAlta` = STR_TO_DATE('01/02/2021','%d/%m/%Y') ,`fechaUltConexion` = STR_TO_DATE('01/01/2000','%d/%m/%Y'), `verificado` = '1';

INSERT INTO `owner_rental_db`.`tiposalojamientos` (`idTipoAlojamiento`, `descripcion`, `habilitado`) VALUES	('1', 'Casa', '1');
INSERT INTO `owner_rental_db`.`tiposalojamientos` (`idTipoAlojamiento`, `descripcion`, `habilitado`) VALUES	('2', 'Cabaña', '1');
INSERT INTO `owner_rental_db`.`tiposalojamientos` (`idTipoAlojamiento`, `descripcion`, `habilitado`) VALUES	('3', 'Departamento', '1');
INSERT INTO `owner_rental_db`.`tiposalojamientos` (`idTipoAlojamiento`, `descripcion`, `habilitado`) VALUES	('4', 'Loft', '1');
INSERT INTO `owner_rental_db`.`tiposalojamientos` (`idTipoAlojamiento`, `descripcion`, `habilitado`) VALUES	('5', 'Suite', '1');
INSERT INTO `owner_rental_db`.`tiposalojamientos` (`idTipoAlojamiento`, `descripcion`, `habilitado`) VALUES	('6', 'Hostel', '1');

INSERT INTO `owner_rental_db`.`publicaciones` 	SET `idPublicacion`= '1', `idUsuario` ='1', `idTipoAlojamiento` ='1', `descripcion` ='Casa - Test', `idLocalidad` ='2544', `codPostal` ='1648', `coordenadas` ='', `calle` ='Av. alguna parte', `altura` ='3000', `piso` ='0', `dpto` ='0', `supCubierta` ='700', `supDescubierta` ='50', `precioExpensas` ='0', `precioNoche` ='700', `cantPersonas` ='4', `cantAmbientes` ='4', `cantBanios` ='2', `cantHabitaciones` ='2', `aniosAntiguedad` ='5', `fechaAlta` =STR_TO_DATE('30/01/2019','%d/%m/%Y'), `puntaje` ='3.5', `habilitado` ='1', `verificado` ='0';
INSERT INTO `owner_rental_db`.`publicaciones` 	SET `idPublicacion`= '2', `idUsuario` ='1', `idTipoAlojamiento` ='1', `descripcion` ='Casa - Tigre', `idLocalidad` ='2545', `codPostal` ='0', `coordenadas` ='', `calle` ='Los pasos', `altura` ='2500', `piso` ='0', `dpto` ='0', `supCubierta` ='450', `supDescubierta` ='40', `precioExpensas` ='1500', `precioNoche` ='400', `cantPersonas` ='3', `cantAmbientes` ='4', `cantBanios` ='1', `cantHabitaciones` ='3', `aniosAntiguedad` ='2', `fechaAlta` =STR_TO_DATE('30/12/2018','%d/%m/%Y'), `puntaje` ='2.5', `habilitado` ='1', `verificado` ='0';
INSERT INTO `owner_rental_db`.`publicaciones` 	SET `idPublicacion`= '3', `idUsuario` ='1', `idTipoAlojamiento` ='4', `descripcion` ='Loft - vteLopez- Disfruta de tus vacaciones en este departamento remodelado y pensado en cada detalle para que tu estancia sea muy cómoda e inolvidable. El departamento es muy luminoso y cálido. La cocina y la sala de estar están bien equipadas.', `idLocalidad` ='2896', `codPostal` ='0', `coordenadas` ='', `calle` ='Av. Libertador', `altura` ='2000', `piso` ='0', `dpto` ='0', `supCubierta` ='500', `supDescubierta` ='50', `precioExpensas` ='2000', `precioNoche` ='750', `cantPersonas` ='4', `cantAmbientes` ='6', `cantBanios` ='2', `cantHabitaciones` ='4', `aniosAntiguedad` ='3', `fechaAlta` =STR_TO_DATE('01/01/2019','%d/%m/%Y'), `puntaje` ='4', `habilitado` ='1', `verificado` ='1';
INSERT INTO `owner_rental_db`.`publicaciones` 	SET `idPublicacion`= '4', `idUsuario` ='2', `idTipoAlojamiento` ='3', `descripcion` ='Depto - San isi', `idLocalidad` ='2278', `codPostal` ='1646', `coordenadas` ='', `calle` ='Reconquista', `altura` ='1500', `piso` ='4', `dpto` ='b', `supCubierta` ='500', `supDescubierta` ='50', `precioExpensas` ='0', `precioNoche` ='800', `cantPersonas` ='5', `cantAmbientes` ='6', `cantBanios` ='2', `cantHabitaciones` ='4', `aniosAntiguedad` ='1', `fechaAlta` =STR_TO_DATE('01/01/2019','%d/%m/%Y'), `puntaje` ='5', `habilitado` ='1', `verificado` ='1';
INSERT INTO `owner_rental_db`.`publicaciones` 	SET `idPublicacion`= '5', `idUsuario` ='2', `idTipoAlojamiento` ='2', `descripcion` ='Cabaña en sanFer', `idLocalidad` ='2278', `codPostal` ='1646', `coordenadas` ='', `calle` ='Pinos', `altura` ='1000', `piso` ='0', `dpto` ='0', `supCubierta` ='150', `supDescubierta` ='60', `precioExpensas` ='0', `precioNoche` ='450', `cantPersonas` ='4', `cantAmbientes` ='3', `cantBanios` ='1', `cantHabitaciones` ='2', `aniosAntiguedad` ='5', `fechaAlta` =STR_TO_DATE('01/01/2019','%d/%m/%Y'), `puntaje` ='4.5', `habilitado` ='1', `verificado` ='1';
INSERT INTO `owner_rental_db`.`publicaciones` 	SET `idPublicacion`= '6', `idUsuario` ='4', `idTipoAlojamiento` ='1', `descripcion` ='Casa Hostel - Bed and Breakfast(B&B)', `idLocalidad` ='2278', `codPostal` ='0', `coordenadas` ='', `calle` ='san justo', `altura` ='500', `piso` ='1', `dpto` ='c', `supCubierta` ='80', `supDescubierta` ='0', `precioExpensas` ='0', `precioNoche` ='200', `cantPersonas` ='2', `cantAmbientes` ='2', `cantBanios` ='1', `cantHabitaciones` ='1', `aniosAntiguedad` ='6', `fechaAlta` =STR_TO_DATE('01/01/2019','%d/%m/%Y'), `puntaje` ='3.5', `habilitado` ='1', `verificado` ='0';
INSERT INTO `owner_rental_db`.`publicaciones` 	SET `idPublicacion`= '7', `idUsuario` ='4', `idTipoAlojamiento` ='4', `descripcion` ='Loft en Tigre. Disfrutá su estilo moderno', `idLocalidad` ='2897', `codPostal` ='0', `coordenadas` ='', `calle` ='Uruguay', `altura` ='250', `piso` ='0', `dpto` ='0', `supCubierta` ='650', `supDescubierta` ='50', `precioExpensas` ='245', `precioNoche` ='960', `cantPersonas` ='5', `cantAmbientes` ='2', `cantBanios` ='3', `cantHabitaciones` ='4', `aniosAntiguedad` ='1', `fechaAlta` =STR_TO_DATE('01/01/2019','%d/%m/%Y'), `puntaje` ='5', `habilitado` ='1', `verificado` ='0';

INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('4', '1', 'comentario - test 1', STR_TO_DATE('30/11/2018','%d/%m/%Y'), '5', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('2', '1', 'Una casa buena, fácil para llegar y con todo lo necesario', STR_TO_DATE('30/11/2018','%d/%m/%Y'), '5', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('3', '2', 'comentario - test 3', STR_TO_DATE('30/12/2018','%d/%m/%Y'), '3', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('4', '2', 'Lugar Buenísimo, cerca de todo, muy privado, Cómodo, Los Anfitriones siempre atentos a los posibles requerimientos. Hay Cocina, refrigerador, y baño privado. Excelente!!! Volveré!!!', STR_TO_DATE('13/01/2019','%d/%m/%Y'), '5', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('5', '2', 'Hermosa casa y personas, muy amables.. Gracias x todo!', STR_TO_DATE('08/01/2019','%d/%m/%Y'), '4', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('1', '4', 'Excelente ubicación, comodidad, privacidad.', STR_TO_DATE('04/01/2019','%d/%m/%Y'), '4', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('2', '4', 'El apartamento esta muy bien ubicado funcionado todo muy limpio y tranquillo de noche para nada ruidoso', STR_TO_DATE('04/01/2019','%d/%m/%Y'), '4', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('3', '4', 'Hermoso lugar! Impecable en todo los detalles. La ubicación es ideal. Se nota la dedicación y generosidad', STR_TO_DATE('04/01/2019','%d/%m/%Y'), '5', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('4', '4', 'Un espacio acogedor, limpio, práctico con todo lo necesario para una excelente estadía. el depto es exactamente igual qie en las fotos, incluso mas lindo. ', STR_TO_DATE('02/01/2019','%d/%m/%Y'), '5', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('5', '4', 'Todo perfecto. Comunicación rápida y departamento impecable', STR_TO_DATE('04/01/2019','%d/%m/%Y'), '5', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('1', '5', 'La atención es muy buena, el lugar limpio y mas que agradable, un lugar ideal para descansar y desenchufarse !', STR_TO_DATE('04/01/2019','%d/%m/%Y'), '5', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('4', '5', 'Mejor imposible, lo recomiendo 100%..quede fascinada... espero volver ', STR_TO_DATE('12/01/2019','%d/%m/%Y'), '5', '1');
INSERT INTO `owner_rental_db`.`comentarios` (`idUsuario`, `idPublicacion`, `descripcion`, `fechaComentario`, `puntaje`, `habilitado`) VALUES	('5', '5', 'Ideal para desconectar, las cabañas tienen intimidad a pesar de estar en el mismo predio, y la pileta y la posibilidad de salir en kayaks a pasear libremente por los arroyos suma muchísimo a la experiencia. Recomiendo llevar lo que precisen para cocina', STR_TO_DATE('03/01/2019','%d/%m/%Y'), '5', '1');
