<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title></title>
</head>
<body>
	<div>
		<table>
			<thead>
				<tr>
					<th>idSolicitud</th>
					<th>idUsuarioHuesped</th>
					<th>idPublicacion</th>
					<th>fechaReservaInicio</th>
					<th>fechaReservaFin</th>
					<th>cantDiasReserva</th>
					<th>cantPersonas</th>
					<th>precioFinal</th>
					<th>fechaAltaSolicitud</th>
					<th>idUsuarioPropietario</th>
					<th>fechaDecisionPropietario</th>
					<th>motivoDecisionPropietario</th>
					<th>idEstadoSolicitud</th>
					<th>habilitado</th>
				</tr>
			</thead>
			<tbody>
				<c:forEach items="${listaSolDeReservaEnviada}" var="objSolReserva">
					<tr>
						<td>${objSolReserva.idSolicitud}</td>
						<td>${objSolReserva.idUsuarioHuesped}</td>
						<td>${objSolReserva.idPublicacion}</td>
						<td>${objSolReserva.fechaReservaInicio}</td>
						<td>${objSolReserva.fechaReservaFin}</td>
						<td>${objSolReserva.cantDiasReserva}</td>
						<td>${objSolReserva.cantPersonas}</td>
						<td>${objSolReserva.precioFinal}</td>
						<td>${objSolReserva.fechaAltaSolicitud}</td>
						<td>${objSolReserva.idUsuarioPropietario}</td>
						<td>${objSolReserva.fechaDecisionPropietario}</td>
						<td>${objSolReserva.motivoDecisionPropietario}</td>
						<td>${objSolReserva.idEstadoSolicitud}</td>
						<td>${objSolReserva.habilitado}</td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
	</div>
</body>
</html>